### ISSUE TITLE
Actual CFL Trades

### ISSUE THREAD

**Issue by 49ersAlouettes** [pudds/110yards#16]
Since Toliver is out this week, I went to put Chris Williams in my lineup but the site still thinks he is on Montreal and he is therefore locked. When are traded players typically changed on the fantasy site?

**Comment by pudds** [comment]
The teams come from the CFL API, but I think they are only updated a couple
times a week (can't remember exactly).  It will be picked up for next week,
but I can't change it for this week.

On Jul. 27, 2018 7:29 p.m., "49ersAlouettes" <notifications@github.com>
wrote:

Since Toliver is out this week, I went to put Chris Williams in my lineup
but the site still thinks he is on Montreal and he is therefore locked.
When are traded players typically changed on the fantasy site?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pudds/110yards/issues/16>, or mute the thread
