### ISSUE TITLE
Cfl fantasy

### ISSUE THREAD

**Issue by redblacks** [pudds/110yards#6]
Hey.  We would like to thank toy for making this site.   We were using fantaseh for 5 yrs before and did it manually on excell sheet last year ...   just wondering how we add out 2nd running back.   We play with one starter and one oin bench for bye week reasons.  Any way this can be down.  We're redblacks fantasy league name.  Thanks Nick

**Comment by pudds** [comment]
Hey, glad you like the site.

Rosters are limited to 1 qb, 1 RB and 1 kicker for balance reasons.  You can get around the limit one of two ways: you can use bye slot(s), which allow you to sit a player who's on bye for the week and pick up another (kind of like an injury reserve, but for bye weeks), or you can just use the IR, which isn't actually limited to players who are injured, since the CFL doesn't provide up to date data for that.

I'd recommend using the bye slot, and having managers pick up running backs as needed throughput the season, but using the IR as a place to stash a running back will work just fine too.

**Comment by redblacks** [comment]
Awsome thanks for the quick response .....I'll give it a try.   The other thing we were wondering is  their a setting were we can change the point system.  We're used to playing with 6pt qb touchdowns and 3pt feild goals.    .....almost all the setting are the same as those in "Admins choice scoring" except those 2 

Sent from Yahoo Mail on Android 
 
  On Wed, 13 Jun 2018 at 11:36 PM, pudds<notifications@github.com> wrote:   
Hey, glad you like the site.

Rosters are limited to 1 qb, 1 RB and 1 kicker for balance reasons. You can get around the limit one of two ways: you can use bye slot(s), which allow you to sit a player who's on bye for the week and pick up another (kind of like an injury reserve, but for bye weeks), or you can just use the IR, which isn't actually limited to players who are injured, since the CFL doesn't provide up to date data for that.

I'd recommend using the bye slot, and having managers pick up running backs as needed throughput the season, but using the IR as a place to stash a running back will work just fine too.

**Comment by pudds** [comment]
Sorry, I ran out of time on that one.  Next year I'll offer custom scoring, for this season only the three options are available

**Comment by redblacks** [comment]
Ok that's better than doing it on an excel sheet lmao.   Thanks so much for putting this together.   All 6 of us just finished our live draft   ....... Did u build this site ur self?

Sent from Yahoo Mail on Android 
 
  On Wed, 13 Jun 2018 at 11:43 PM, pudds<notifications@github.com> wrote:   
Sorry, I ran out of time on that one. Next year I'll offer custom scoring, for this season only the three options are available

**Comment by pudds** [comment]
Right on.  Did the draft go smoothly?

Yes, this is a custom built site.  I built it last year for our league, but wasn't ready to go public with it.

**Comment by redblacks** [comment]
Man its really good were impressed forsure.     Yea it went good.   We did it on a white board in my garage so that we can talk smack to each other haha..... One guy drafted Chambers.  To bad he's done for the year lmao.

Sent from Yahoo Mail on Android 
 
  On Wed, 13 Jun 2018 at 11:54 PM, pudds<notifications@github.com> wrote:   
Right on. Did the draft go smoothly?

Yes, this is a custom built site. I built it last year for our league, but wasn't ready to go public with it.

**Comment by redblacks** [comment]
I added all our 2nd  runningbacks in IR slots thinks it's gonna work fine   thanks.   Not sure if u use them bust @cflnews @3downnation is good for updates 

Sent from Yahoo Mail on Android 
 
  On Wed, 13 Jun 2018 at 11:56 PM, Nick Richmond<avs_rule33@rogers.com> wrote:   Man its really good were impressed forsure.     Yea it went good.   We did it on a white board in my garage so that we can talk smack to each other haha..... One guy drafted Chambers.  To bad he's done for the year lmao.

Sent from Yahoo Mail on Android 
 
  On Wed, 13 Jun 2018 at 11:54 PM, pudds<notifications@github.com> wrote:   
Right on. Did the draft go smoothly?

Yes, this is a custom built site. I built it last year for our league, but wasn't ready to go public with it.

**Comment by redblacks** [comment]
Hey. Just wondering if we can get duron Carter switched back to WR he is  listed as a dB now in our league.    League name is redblacks fantasy thanks

**Comment by pudds** [comment]
The site uses the official CFL designation.  If he gets changed in the API,
it will be reflected on the site.

On Jul. 17, 2018 5:10 p.m., "redblacks" <notifications@github.com> wrote:

Hey. Just wondering if we can get duron Carter switched back to WR he is
listed as a dB now in our league.    League name is redblacks
fantasy thanks

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/pudds/110yards/issues/6#issuecomment-405744846>, or mute
the thread
